# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np

arr = np.loadtxt("minutes_n_ingredients.csv", delimiter=',', dtype=np.int32, skiprows=1)
print(arr[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
mean = np.mean(arr, axis=0)
min = np.min(arr, axis=0)
max = np.max(arr, axis=0)
med = np.median(arr, axis=0)

print(float(mean[1]), float(mean[2]))
print(float(min[1]), float(min[2]))
print(float(max[1]), float(max[2]))
print(float(med[1]), float(med[2]))


21601.00169 9.05528
0.0 1.0
2147483647.0 39.0
40.0 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [5]:
qn75 = np.quantile(arr[:, 1], 0.75)
arr2 = arr.copy()
arr2[:,1] = np.clip(arr2[:,1],a_max=qn75, a_min=None)
print(arr2)


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [16]:
arr_zero = np.where(arr[:,1] == 0)[0]
print(len(arr_zero))

arr3 = arr.copy()
arr3[arr_zero, 1] = 1
print(arr3)



479
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [20]:
arr_colum12 = np.column_stack((arr[:,1], arr[:,2]))
print(arr_colum12)
print(len(np.unique(arr_colum12)))

[[ 60  16]
 [ 25   7]
 [ 10   6]
 ...
 [ 65  15]
 [  5   4]
 [140  14]]
656


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [24]:
unic = np.unique(arr[:,2], return_counts=True)
print(len(unic[0]))
unic

37


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 37, 39], dtype=int32),
 array([   13,   926,  2895,  5515,  7913,  9376, 10628, 10951, 10585,
         9591,  8297,  6605,  4997,  3663,  2595,  1767,  1246,   790,
          573,   376,   217,   161,   105,    69,    50,    28,    16,
           16,    12,    12,     3,     1,     2,     1,     3,     1,
            1]))

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [27]:
ar = np.where(arr[:,2]<=5)[0]
arr5 = arr[ar,:]
print(arr5)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [36]:
ar = arr3[:, 2] / arr3[:, 1]

print(ar)
np.max(ar)

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [43]:
arg = np.argsort(arr[:,1])
arr9 = arr[arg]
arr9 = arr9[-1:-101:-1]
np.mean(arr9[:,2])


6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [44]:
np.random.shuffle(arr)
arr[:10]

array([[ 73749,     90,      6],
       [503955,     75,     14],
       [141169,     75,     13],
       [360579,     70,     19],
       [371774,     20,      5],
       [159617,     30,     10],
       [226523,     30,     12],
       [112813,    190,      3],
       [304916,     35,      7],
       [204589,    210,     12]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [51]:
mean = np.mean(arr[:,2])
ind = np.where(arr[:,2]<mean)[0]
print(f"{len(ind)*100/len(arr)}%")

58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [59]:
sample = ((arr[:,1]<=20) & (arr[:,2]<=5))
sample = cmp.astype(int)
arr12 = np.column_stack((arr, sample))
arr12



array([[ 73749,     90,      6,      0],
       [503955,     75,     14,      0],
       [141169,     75,     13,      0],
       ...,
       [119965,     25,     20,      0],
       [ 62746,    750,     13,      0],
       [343257,     13,      7,      0]])

13. Выведите процент "простых" рецептов в датасете

In [65]:
ind = np.where(sample[:] == 1 )[0]
len(ind)*100/len(sample)

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [74]:
sh = arr[arr[:,2]<10]
st = arr[(arr[:,2]>=10)&(arr[:,2]<20)]
lg = arr[arr[:,2]>=20]

axis1 = np.min([len(sh), len(st), len(lg)])
Arr = np.zeros((3, axis1, 3), dtype=np.int32)

Arr[0,:,:] = sh[:axis1]
Arr[1,:,:] = st[:axis1]
Arr[2,:,:] = lg[:axis1]

print(Arr)


[[[ 73749     90      6]
  [371774     20      5]
  [112813    190      3]
  ...
  [ 37972     15      7]
  [293373      5      8]
  [295737     40      4]]

 [[503955     75     14]
  [141169     75     13]
  [360579     70     19]
  ...
  [ 60828     50     19]
  [ 60982    135     12]
  [ 33786     45     13]]

 [[149055     65     30]
  [475043     65     20]
  [ 80358    150     27]
  ...
  [282044    210     21]
  [211595     65     21]
  [119965     25     20]]]
